[package]
name = "_accelerate"
version = "0.1.0"
edition = "2018"

[lib]
name = "_accelerate"
crate-type = ["cdylib"]

[dependencies]
rayon = "1.8"
pyo3 = { version = "0.24" , features = ["abi3-py310", "extension-module", "macros"] }
numpy   = "0.24"
num-complex = "0.4"
hashbrown = "0.15"
