name: Latest version tests

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'
  schedule:
    - cron: '0 1 * * *'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
        include:
          - os: macos-latest
            python-version: "3.10"
    steps:
      - uses: actions/checkout@v4
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path qiskit_addon_sqd/_accelerate/Cargo.toml
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and build Rust extension
        run: |
          python -m pip install --upgrade pip
          pip install tox maturin
      - name: Build wheel with maturin
        run: maturin build --release --manifest-path qiskit_addon_sqd/_accelerate/Cargo.toml
      - name: Install wheel
        run: pip install qiskit_addon_sqd/_accelerate/target/wheels/*.whl
      - name: Test using tox environment
        shell: bash
        run: |
          tox -e py,notebook --parallel --parallel-no-spinner
