name: Latest version tests

on:
  push:
    branches:
      - main
      - 'stable/**'
  pull_request:
    branches:
      - main
      - 'stable/**'
  schedule:
    - cron: '0 1 * * *'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
        include:
          - os: macos-latest
            python-version: "3.10"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
        run: |
          python -m pip install --upgrade pip
          pip install tox
          pip install maturin
      - name: Install package
        run: maturin develop
      - name: Test using tox environment
        shell: bash
        run: |
          tox -e py,notebook --parallel --parallel-no-spinner
